version: '3.8'

services:
  nginx:
    image: nginx
    container_name: dashboard
    volumes:
      - './dist/Dashboard:/var/www/Dashboard'
      - './assets:/var/www/Dashboard/assets'
      - './nginx.conf:/etc/nginx/conf.d/nginx.conf'
    ports:
      - '4900:4900'
